"""Reproducible OFL font vendoring from a pinned Google Fonts GitHub revision.
Requires authenticated gh, downloads only selected TTF + licenses, never whole datasets.
The generated source manifest records SHA-256 and the exact upstream revision.
"""
import base64
import hashlib
import json
from pathlib import Path
import subprocess

FAMILIES = [
 ('spacegrotesk','Space Grotesk','modern'),('dmsans','DM Sans','modern'),('manrope','Manrope','minimal'),
 ('plusjakartasans','Plus Jakarta Sans','modern'),('outfit','Outfit','modern'),('syne','Syne','creative'),
 ('urbanist','Urbanist','minimal'),('sora','Sora','modern'),('unbounded','Unbounded','display'),
 ('montserrat','Montserrat','signage'),('raleway','Raleway','elegant'),('oswald','Oswald','industrial'),
 ('anton','Anton','bold'),('bebasneue','Bebas Neue','bold'),('barlowcondensed','Barlow Condensed','industrial'),
 ('barlow','Barlow','signage'),('archivo','Archivo','signage'),('archivoblack','Archivo Black','bold'),
 ('leaguegothic','League Gothic','retro'),('leaguespartan','League Spartan','bold'),
 ('playfairdisplay','Playfair Display','luxury'),('cormorantgaramond','Cormorant Garamond','elegant'),
 ('bodonimoda','Bodoni Moda','luxury'),('cinzel','Cinzel','luxury'),('marcellus','Marcellus','elegant'),
 ('prata','Prata','luxury'),('librebaskerville','Libre Baskerville','classic'),('ebgaramond','EB Garamond','classic'),
 ('dmserifdisplay','DM Serif Display','luxury'),('abrilfatface','Abril Fatface','display'),
 ('lobster','Lobster','retro'),('pacifico','Pacifico','handwritten'),('caveat','Caveat','handwritten'),
 ('kalam','Kalam','handwritten'),('allura','Allura','handwritten'),
 ('notosansarabic','Noto Sans Arabic','arabic'),('notonaskharabic','Noto Naskh Arabic','arabic'),
 ('cairo','Cairo','arabic'),('tajawal','Tajawal','arabic'),('amiri','Amiri','arabic'),
 ('readexpro','Readex Pro','bilingual'),('lateef','Lateef','arabic'),('changa','Changa','arabic'),
 ('reemkufi','Reem Kufi','arabic'),('arefruqaa','Aref Ruqaa','arabic'),
]
def api(path):
 return json.loads(subprocess.check_output(['gh','api',path]))
def contents(path,ref):
 value=api(f'repos/google/fonts/contents/{path}?ref={ref}')
 if not value.get('content'):
  value=api(f"repos/google/fonts/git/blobs/{value['sha']}")
 return base64.b64decode(value['content'])
root=Path(__file__).resolve().parent.parent
manifest=root/'src/design/fonts/catalogue.ts'
# First run pins current revision. Subsequent runs read the committed pin rather than floating main.
pinfile=root/'public/fonts/UPSTREAM.json'
if pinfile.exists(): ref=json.loads(pinfile.read_text())['revision']
else: ref=api('repos/google/fonts/commits/main')['sha']
pinfile.parent.mkdir(parents=True,exist_ok=True)
pinfile.write_text(json.dumps(dict(repository='google/fonts',revision=ref,license='SIL Open Font License 1.1'),indent=2)+'\n')
items=[]
for index,(key,name,category) in enumerate(FAMILIES):
 directory=f'ofl/{key}'
 entries=api(f'repos/google/fonts/contents/{directory}?ref={ref}')
 candidates=[e for e in entries if e['name'].endswith('.ttf') and 'Italic' not in e['name'] and 'italic' not in e['name']]
 candidates.sort(key=lambda e:(0 if 'Regular' in e['name'] else 1,e['name']))
 if not candidates: raise RuntimeError(f'No regular TTF for {key}')
 existing=root/f'public/fonts/{key}.ttf'
 existing_data=existing.read_bytes() if existing.exists() else b''
 git_hash=hashlib.sha1(b'blob '+str(len(existing_data)).encode()+b'\0'+existing_data).hexdigest()
 font=existing_data if git_hash==candidates[0]['sha'] else contents(candidates[0]['path'],ref)
 if len(font)>4_000_000: raise RuntimeError(f'Font too large: {key}')
 license_data=contents(directory+'/OFL.txt',ref)
 if b'SIL OPEN FONT LICENSE' not in license_data.upper(): raise RuntimeError(f'Unverified license: {key}')
 path=root/f'public/fonts/{key}.ttf'
 path.parent.mkdir(parents=True,exist_ok=True)
 path.write_bytes(font)
 license_path=root/f'public/fonts/licenses/{key}.txt'
 license_path.parent.mkdir(parents=True,exist_ok=True)
 license_path.write_bytes(license_data)
 items.append(dict(id=key,name=name,category=category,url=f'/fonts/{key}.ttf',license=f'/fonts/licenses/{key}.txt',sha256=hashlib.sha256(font).hexdigest(),source=f'https://github.com/google/fonts/blob/{ref}/{candidates[0]["path"]}',arabic=category in ['arabic','bilingual'],normal=index<24 or category in ['arabic','bilingual']))
 print(f'{name}: {len(font):,} bytes, OFL verified',flush=True)
pinfile.write_text(json.dumps(dict(repository='google/fonts',revision=ref,license='SIL Open Font License 1.1'),indent=2)+'\n')
manifest.parent.mkdir(parents=True,exist_ok=True)
manifest.write_text('// Generated by scripts/vendor-fonts.py. Licensed sources and checksums are recorded below.\nexport const FONT_CATALOGUE = '+json.dumps(items,ensure_ascii=False,indent=2)+' as const;\nexport type FontId = (typeof FONT_CATALOGUE)[number]["id"];\n')
print(f'Vendored {len(items)} licensed fonts at {ref}.')
